kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: k8
    trainer: pavan
  annotations:
    kubernetes.io/created-by: 'pavan'
    jenkins.build.url: 'https://jenkins.pavanv93.online/expense/job/backend/54'
spec:
  containers:
  - name: nginx
    image: nginx